import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wamaps",
  description: "Generated by Wamaps",
  verification: {
    other: {
      "facebook-domain-verification": ["mzwb042vygfl9n76og7w6i2bj6s8yb"],
    },
  },
};

import { Toaster } from "sonner";
import FacebookPixel from "@/components/FacebookPixel";
import { Suspense } from "react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <FacebookPixel />
        </Suspense>
        <Toaster position="top-right" richColors closeButton />
        {children}
      </body>
    </html>
  );
}
